# Generated by Django 4.2.3 on 2023-07-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_alter_chat_users_alter_message_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
